version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '55432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=bd
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
